### ISSUE TITLE
Cannot connect to device

### ISSUE THREAD

**Issue by thecivvie** [uugear/UUGear-Web-Interface#1]
I installed and rebooted my Pi and the web UI is saying that it cannot connect to the device. I have the Omni unit attached

**Comment by uugear** [comment]
Please make sure your device and software has been installed properly. You can run zero2go.sh and see if it works.

Then check the content of uwi.conf file. More specifically if the web_socket_url is pointing to correct address, and the zero2go variable is pointing to the correct directory.

**Comment by thecivvie** [comment]
I think the issue is not connecting to the Omni but something to do with the Pi

**Comment by humanIntellisense** [comment]
![image](https://user-images.githubusercontent.com/2512165/97851838-9448c500-1cfe-11eb-964b-20f390ece301.png)

**Comment by humanIntellisense** [comment]
Same here raspberry pi os lite fresh install. Witty pi 3 works fine from ./wittyPi.sh

**Comment by humanIntellisense** [comment]
Ah OK i fixed it. You have to go to uwi.conf and set host='YOUR CURRENT HOSTNAME or IP'; and it will work as expected. I changed my hostname so websocket Failed. I think you can close the issue.

**Comment by thecivvie** [comment]
Excellent. my bad :)

**Comment by 3ricj** [comment]
> Ah OK i fixed it. You have to go to uwi.conf and set host='YOUR CURRENT HOSTNAME or IP'; and it will work as expected. I changed my hostname so websocket Failed. I think you can close the issue.

It's possible the enhancement I proposed in #4 could prevent this problem from happening in the future.
